pypro/aperitivos/urls.py
from django.urls import path

from pypro.aperitivos.views import video, indice

app_name = 'aperitivos'
urlpatterns = [
    path('<slug:slug>', video, name='video'),
    path('', indice, name='indice'),
]

pypro/base/urls.py
from django.urls import path

from pypro.base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home')

]

pypro/modulos/urls.py
from django.urls import path

from pypro.modulos import views

app_name = 'modulos'
urlpatterns = [
    path('<slug:slug>', views.detalhe, name='detalhe'),
    path('aula/<slug:slug>', views.aula, name='aula'),
    path('', views.indice, name='indice'),
]

pypro/turmas/urls.py
from django.urls import path

from pypro.turmas import views

app_name = 'turmas'
urlpatterns = [
    path('', views.indice, name='indice'),
]

pypro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pypro.base.urls')),
    path('aperitivos/', include('pypro.aperitivos.urls')),
    path('modulos/', include('pypro.modulos.urls')),
    path('turmas/', include('pypro.turmas.urls')),
    path('contas/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

pypro/aperitivos/models.py
from django.db import models
from django.urls import reverse


class Video(models.Model):
    titulo = models.CharField(max_length=32)
    slug = models.SlugField(max_length=32)
    vimeo_id = models.CharField(max_length=32)
    creation = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('aperitivos:video', args=(self.slug,))

    def __str__(self):
        return f'Video {self.titulo}'

pypro/base/models.py
# Create your models here.
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **kwargs):
        """
        Creates and saves user with given email and password.
        """

        if not email:
            raise ValueError('The given email must be set.')
        email = self.normalize_email(email)
        user = self.model(email=email, **kwargs)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, **kwargs):
        kwargs.setdefault('is_superuser', False)
        return self._create_user(email, password, **kwargs)

    def create_superuser(self, email, password, **kwargs):
        kwargs.setdefault('is_superuser', True)
        kwargs.setdefault('is_staff', True)

        if kwargs.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')
        if kwargs.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True')

        return self._create_user(email, password, **kwargs)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class

    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

pypro/modulos/models.py
from django.db import models
from django.urls import reverse
from ordered_model.models import OrderedModel


# Create your models here.
class Modulo(OrderedModel):
    titulo = models.CharField(max_length=64)
    publico = models.TextField()
    descricao = models.TextField()
    slug = models.SlugField(unique=True)

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('modulos:detalhe', kwargs={'slug': self.slug})


class Aula(OrderedModel):
    titulo = models.CharField(max_length=64)
    slug = models.SlugField(unique=True)
    modulo = models.ForeignKey('Modulo', on_delete=models.PROTECT)
    order_with_respect_to = 'modulo'
    vimeo_id = models.CharField(max_length=32)

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('modulos:aula', kwargs={'slug': self.slug})

pypro/turmas/models.py
from django.contrib.auth import get_user_model
from django.db import models


# Create your models here.
class Turma(models.Model):
    nome = models.CharField(max_length=64)
    slug = models.SlugField(max_length=64)
    inicio = models.DateField()
    fim = models.DateField()
    alunos = models.ManyToManyField(get_user_model(), through='Matricula')


class Matricula(models.Model):
    data = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    turma = models.ForeignKey(Turma, on_delete=models.CASCADE)

    class Meta:
        unique_together = [['usuario', 'turma']]
        ordering = ['turma', 'data']

pypro/aperitivos/views.py
from django.shortcuts import render, get_object_or_404

from pypro.aperitivos.models import Video


def video(request, slug):
    video = get_object_or_404(Video, slug=slug)
    return render(request, 'aperitivos/video.html', context={'video': video})


def indice(request):
    v = Video.objects.order_by('creation').all()
    return render(request, 'aperitivos/indice.html', context={'videos': v})

pypro/base/views.py
# Create your views here.
from django.shortcuts import render


def home(request):
    return render(request, 'base/home.html')

pypro/modulos/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from pypro.modulos import facade


def indice(request):
    ctx = {'modulos': facade.listar_modulos_com_aulas()}
    return render(request, 'modulos/indice.html', ctx)


def detalhe(request, slug):
    modulo = facade.encontrar_modulo(slug)
    aulas = facade.listar_aulas_de_modulo_ordenadas(modulo)
    return render(request, 'modulos/modulo_detalhe.html', {'modulo': modulo, 'aulas': aulas})


@login_required
def aula(request, slug):
    aula = facade.encontrar_aula(slug)
    return render(request, 'modulos/aula_detalhe.html', {'aula': aula})

pypro/turmas/views.py
from django.shortcuts import render


# Create your views here.
def indice(request):
    return render(request, 'turmas/indice.html')

pypro/aperitivos/templates/aperitivos/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Python Pro - Aperitivos{% endblock %}
{% block description %}Pagina com todos os videos gratuitos{% endblock description %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-4 mb-3">Lista de videos aperitivos</h1>
            <ol>
                {% for v in videos %}
                <li>
                    <a href="{{v.get_absolute_url}}">{{ v.titulo | default:"Faltando Titulo" }}</a>
                </li>
                {% empty %}
                <li>
                    Nenhum video encontrado
                </li>
                {% endfor %}

            </ol>
        </div>
    </div>
</div>
{% endblock body %}

pypro/aperitivos/templates/aperitivos/video.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Python Pro - Aperitivo{% endblock %}
{% block description %}Pagina com video gratuito{% endblock description %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-4 mb-3">{{ video.titulo | default:"Faltando Titulo" }}</h1>
            <iframe allow="autoplay; fullscreen" allowfullscreen
                    frameborder="0" height="360" src="https://player.vimeo.com/video/{{ video.vimeo_id}}"
                    width="640"></iframe>
        </div>
    </div>
</div>
{% endblock body %}

pypro/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1" name="viewport">

    <title>{% block title %}Python Pro{% endblock title %}</title>

    <meta content="{% block description %}Pagina curso pytho pro{% endblock description %}" name="description">
    <meta content="pcampos119104" name="author">

    <link href="{% static 'img/favicon.png' %}" rel="icon" type="image/png"/>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>


</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'base:home' %}">Python Pro</a>
    <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
            class="navbar-toggler"
            data-target="#navbarSupportedContent" data-toggle="collapse" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown"
                   href="#"
                   id="navbarDropdown" role="button">
                    Modulos
                </a>
                <div aria-labelledby="navbarDropdown" class="dropdown-menu">
                    {% for modulo in MODULOS %}
                    <a class="dropdown-item" href="{{modulo.get_absolute_url}}">{{modulo.titulo}}</a>
                    <div class="dropdown-divider"></div>
                    {% endfor %}
                </div>
            </li>
        </ul>
    </div>
    {% if user.is_authenticated %}
    <ul class="navbar-nav">
        <li class="nav-item dropdown">
            <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown"
               href="#"
               id="navbarDropdown" role="button">
                {{ user.first_name }}
            </a>
            <div aria-labelledby="navbarDropdown" class="dropdown-menu">
                <div class="dropdown-item">
                    <a class="btn btn-danger" href="{% url 'logout' %}" type="button">Sair</a>
                </div>
            </div>
        </li>
    </ul>
    {% else %}
    <a class="btn btn-light my-2" href="{% url 'login' %}">Entrar</a>
    {% endif %}
</nav>

{% block body %}{% endblock body%}
{% include 'base/footer.html' %}
</body>
</html>

pypro/base/templates/base/footer.html
<footer class="main-footer mt-5 pt-4">
    <div class="container">
        <div class="row">
            <div class="col">
                <h3> Entre em contato</h3>
                <address>
                    +55 11 xxxxx-xxxx
                    <br/>
                    <a href="mailto:pcampos119104@gmail.com">pcampos119104@gmail.com</a>
                </address>

            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
                {% now 'Y' %} Projeto do curso Python Pro

            </div>
        </div>
    </div>
</footer>

pypro/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Python Pro - Home{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">

            <div class="jumbotron">
                <h2>
                    Curso de Python com Luciano Ramalho
                </h2>
                <!-- INICIO DO BOTAO PAGSEGURO --><a href="https://pag.ae/7WkjSosS4/button" target="_blank"
                                                     title="Pagar com PagSeguro"><img
                    alt="Pague com PagSeguro - é rápido, grátis e seguro!"
                    src="//assets.pagseguro.com.br/ps-integration-assets/botoes/pagamentos/95x45-pagar.gif"/></a>
                <!-- FIM DO BOTAO PAGSEGURO -->
                <h4 class="mt-4">
                    Entre na fila de espera
                </h4>
                <form action="https://codemodi.us17.list-manage.com/subscribe/post?u=4cc4790964397316e89b915d6&amp;id=a47c209e9c"
                      class="form-row align-items-center" id="mc-embedded-subscribe-form" method="post"
                      name="mc-embedded-subscribe-form" novalidate target="_blank">
                    <div class="form-row align-items-center">
                        <div class="col-auto">
                            <label class="sr-only" for="mce-EMAIL">Email</label>
                            <input class="form-control required" id="mce-EMAIL" name="EMAIL"
                                   placeholder="exemplo@email.com" type="email"
                                   value="">
                        </div>

                        <div class="col-auto">
                            <label class="sr-only" for="mce-FNAME">Nome</label>
                            <input class="form-control required" id="mce-FNAME" name="FNAME" placeholder="Nome"
                                   type="text"
                                   value="">
                        </div>
                        <div aria-hidden="true" style="position: absolute; left: -5000px;"><input
                                name="b_4cc4790964397316e89b915d6_a47c209e9c"
                                tabindex="-1"
                                type="text"
                                value=""></div>

                        <div class="col-auto">
                            <input class="btn btn-primary " id="mc-embedded-subscribe" name="subscribe"
                                   type="submit" value="Subscribe">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <h5 class="card-header">
                    Mais detalhes sobre o instrutor
                </h5>
                <div class="card-body">
                    <p class="card-text">
                        <img alt="Foto de Luciano" class="img-thumbnail" src="{% static 'img/luciano.jpg' %}"/>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

pypro/modulos/templates/modulos/aula_detalhe.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Python Pro - Aperitivo{% endblock %}
{% block description %}Pagina com aula gratuito{% endblock description %}
{% block body %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item"><a href="{{ aula.modulo.get_absolute_url }}">{{ aula.modulo.titulo }}</a></li>
        <li aria-current="page" class="breadcrumb-item active">{{ aula.titulo }}</li>
    </ol>
</nav>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-4 mb-3">{{ aula.titulo | default:"Faltando Titulo" }}</h1>
            <iframe allow="autoplay; fullscreen" allowfullscreen
                    frameborder="0" height="360" src="https://player.vimeo.com/video/{{ aula.vimeo_id}}"
                    width="640"></iframe>
        </div>
    </div>
</div>
{% endblock body %}

pypro/modulos/templates/modulos/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}{{ modulo.titulo }}{% endblock %}
{% block description %}Pagina com detalhes do módulo {{ modulo.titulo }}{% endblock description %}
{% block body %}
<div class="container">
    {% for modulo in modulos %}
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-4 mb-3">{{ modulo.titulo }}</h1>
            <dl>
                <dt>Público</dt>
                <dd>{{ modulo.publico }}</dd>
                <dt>Descrição</dt>
                <dd>{{ modulo.descricao }}</dd>
            </dl>
            <h2>Aulas</h2>
            <ol>
                {% for a in modulo.aulas %}
                <li><a href="{{ a.get_absolute_url }}">{{ a.titulo }}</a></li>
                {% endfor %}
            </ol>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock body %}

pypro/modulos/templates/modulos/modulo_detalhe.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}{{ modulo.titulo }}{% endblock %}
{% block description %}Pagina com detalhes do módulo {{ modulo.titulo }}{% endblock description %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-4 mb-3">{{ modulo.titulo }}</h1>
            <dl>
                <dt>Público</dt>
                <dd>{{ modulo.publico }}</dd>
                <dt>Descrição</dt>
                <dd>{{ modulo.descricao }}</dd>
            </dl>
            <h2>Aulas</h2>
            <ol>
                {% for a in aulas %}
                <li><a href="{{ a.get_absolute_url }}">{{ a.titulo }}</a></li>
                {% endfor %}
            </ol>
        </div>
    </div>
</div>
{% endblock body %}

pypro/turmas/templates/turmas/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}{{ modulo.titulo }}{% endblock %}
{% block description %}Pagina com detalhes do módulo {{ modulo.titulo }}{% endblock description %}
{% block body %}
<div class="container">
    {% for modulo in modulos %}
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-4 mb-3">{{ modulo.titulo }}</h1>
            <dl>
                <dt>Público</dt>
                <dd>{{ modulo.publico }}</dd>
                <dt>Descrição</dt>
                <dd>{{ modulo.descricao }}</dd>
            </dl>
            <h2>Aulas</h2>
            <ol>
                {% for a in modulo.aulas %}
                <li><a href="{{ a.get_absolute_url }}">{{ a.titulo }}</a></li>
                {% endfor %}
            </ol>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock body %}